[package]
name = "keccak-hasher"
version = "0.1.1"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]
description = "Keccak-256 implementation of the Hasher trait"
license = "GPL-3.0"

[dependencies]
sophon-types = {version="0.4",registry="susytech"}
tiny-keccak = {version="1.4.2",registry="susytech"}
hash-db = {version="0.11.0",registry="susytech"}
plain_hasher = {version="0.2",registry="susytech"}
