[package]
description = "Atomically cached len(), for use with collections contained in parking_lot Mutex and RwLock"
homepage = "http://superstring.io"
license = "GPL-3.0"
name = "len-caching-lock"
version = "0.1.1"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]

[dependencies]
parking_lot = {version = "0.7",registry="susytech"}
