[package]
description = "HTTP/HTTPS fetching library"
homepage = "http://superstring.io"
license = "GPL-3.0"
name = "fetch"
version = "0.1.0"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]

[dependencies]
futures = {version = "0.1",registry="susytech"}
hyper = {version="~0.12.9",registry="susytech"}
hyper-rustls = {version="0.16.0",registry="susytech"}
http = {version="0.1",registry="susytech"}
log = {version="0.4",registry="susytech"}
tokio = {version="~0.1.8",registry="susytech"}
url = {version="1",registry="susytech"}
bytes = {version="0.4",registry="susytech"}

[features]
default = []
