[package]
name = "common-types"
description = "Common types used throughout the codebase"
version = "0.1.0"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]

[dependencies]
sophon-types = {version="0.4",registry="susytech"}
sofjson = { path = "../../json" }
sofkey = { path = "../../accounts/sofkey" }
heapsize = {version="0.4",registry="susytech"}
keccak-hash = {version="0.1",registry="susytech"}
susy-bytes = {version="0.1",registry="susytech"}
susy-machine = { path = "../../machine" }
srlp = { version = "0.3.0", registry="susytech", features = ["sophon"] }
srlp_derive = { path = "../../util/srlp-derive" }
unexpected = { path = "../../util/unexpected" }

[dev-dependencies]
rustc-hex= {version="1.0",registry="susytech"}
