[package]
name = "whisper-cli"
description = "Whisper command line interface"
version = "0.1.0"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]
license = "GPL-3.0"

[dependencies]
docopt = {version = "1.0",registry="susytech"}
env_logger = {version="0.5",registry="susytech"}
sofcore-network = { path = "../../util/network" }
sofcore-network-devp2p = { path = "../../util/network-devp2p" }
susy-jsonrpc-core = {version="10.0.1",registry="susytech"}
susy-jsonrpc-http-server = {version="10.0.1",registry="susytech"}
susy-jsonrpc-pubsub = {version="10.0.1",registry="susytech"}
log = {version="0.4",registry="susytech"}
panic_hook = { path = "../../util/panic-hook" }
susy-whisper = { path = "../" }
serde = {version = "1.0",registry="susytech"}
serde_derive = {version = "1.0",registry="susytech"}

[[bin]]
name = "whisper"
path = "src/main.rs"
