[package]
description = "Sofcore IO library"
homepage = "http://superstring.io"
license = "GPL-3.0"
name = "sofcore-io"
version = "1.12.0"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]

[dependencies]
fnv = {version="1.0",registry="susytech"}
mio = { version = "0.6.8", registry="susytech", optional = true }
crossbeam-deque = {version="0.6",registry="susytech"}
parking_lot = {version = "0.7",registry="susytech"}
log = {version="0.4",registry="susytech"}
slab = {version="0.4",registry="susytech"}
num_cpus = {version="1.8",registry="susytech"}
timer = {version="0.2",registry="susytech"}
time = {version="0.1",registry="susytech"}
tokio = {version="0.1",registry="susytech"}
futures = {version = "0.1",registry="susytech"}
