[package]
description = "Sofcore network library"
homepage = "http://superstring.io"
license = "GPL-3.0"
name = "sofcore-network"
version = "1.12.0"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]

[dependencies]
error-chain = { version = "0.12", registry="susytech", default-features = false }
susy-crypto = {version="0.3.0",registry="susytech"}
sofcore-io = { path = "../io" }
sophon-types = {version="0.4",registry="susytech"}
sofkey = { path = "../../accounts/sofkey" }
ipnetwork = {version="0.12.6",registry="susytech"}
lazy_static = {version="1.0",registry="susytech"}
srlp = { version = "0.3.0", registry="susytech", features = ["sophon"] }
libc = {version="0.2",registry="susytech"}
susy-snappy = {version="0.1",registry="susytech"}
semver = {version="0.9.0", registry="susytech", features=["serde"]}
serde = {version = "1.0",registry="susytech"}
serde_derive = {version = "1.0",registry="susytech"}

[dev-dependencies]
assert_matches = {version="1.2",registry="susytech"}
