[package]
name = "swasm-run-test"
version = "0.1.0"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]

[dependencies]
serde = {version="1",registry="susytech"}
serde_json = {version="1",registry="susytech"}
serde_derive = {version="1",registry="susytech"}
sophon-types = {version="0.4",registry="susytech"}
sofjson = { path = "../../../json" }
vm = { path = "../../vm" }
wasm = { path = "../" }
clap = {version="2.24",registry="susytech"}
env_logger = {version="0.5",registry="susytech"}
rustc-hex = {version="1",registry="susytech"}

[features]
default = ["sophon-types/std"]
