[package]
name = "sofcore-bloom-journal"
version = "0.1.0"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]
description = "Journaling bloom filter"
license = "GPL3"

[lib]
path = "src/lib.rs"

[dependencies]
siphasher = {version="0.1.1",registry="susytech"}
