[package]
name = "migration-rocksdb"
version = "0.1.0"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]

[dependencies]
log = {version="0.4",registry="susytech"}
macros = { path = "../macros" }
susykv = {version="0.1",registry="susytech"}
susykv-rocksdb = {version="0.1.3",registry="susytech"}

[dev-dependencies]
tempdir = {version="0.3",registry="susytech"}
