[package]
name = "susy-machine"
version = "0.1.0"
description = "Generalization of a state machine for consensus engines"
authors = ["Susytech <admin@superstring.ch>", "Paritytech <admin@parity.io>"]

[dependencies]
sophon-types = {version="0.4",registry="susytech"}
